version: '2'

networks:
  giraffe:

services:
  giraffe-db:
    image: giraffe
    build: ./db
    cpuset: 0,1
    mem_limit: 512M
    networks:
      - giraffe
    ports:
      - '20000:5432'
    command: postgres -c shared_preload_libraries=pg_stat_statements -c log_min_duration_statement=0
    environment:
      POSTGRES_INITDB_ARGS: '-E UTF8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8'

  giraffe-watchdog:
    image: giraffe-watchdog
    build: ./watchdog
    networks:
      - giraffe
    command:
      - /usr/local/bin/giraffe
      - --cluster=postgresql://postgres@giraffe-db/giraffe
      - --receiver=http://giraffe-api:1984

  giraffe-api:
    image: giraffe-api
    build: ./receiver
    networks:
      - giraffe
    ports:
      - '1984:1984'

  giraffe-gui:
    image: giraffe-gui
    build: ./gui
    networks:
      - giraffe
    ports:
      - '1985:80'
